import const

#ピン番号の指定
const.LEFT_MOTOR_VREF_PIN = 1
const.LEFT_MOTOR_IN1_PIN = 2
const.LEFT_MOTOR_IN2_PIN = 3
const.RIGHT_MOTOR_VREF_PIN = 4
const.RIGHT_MOTOR_IN1_PIN = 5
const.RIGHT_MOTOR_IN2_PIN = 6
const.RED_LED_PIN = 25
const.BLUE_LED_PIN = 26
const.GREEN_LED_PIN = 20
const.RELEASING_PIN = 7
const.BURNING_PIN = 8
const.FLIGHTPIN_PIN = 9


#シークエンス
const.PREPARING = 0
const.FLYING = 1
const.DROPPING = 2
const.LANDING = 3
const.RUNNING = 4
const.GOAL = 5

#閾値
const.PREPARING_TIME_THRE = 10
const.ACC_THRE = 1
const.COUNT_ACC_LOOP_THRE = 50
const.COUNT_FLIGHTPIN_THRE = 10
const.LANDING_TIME_THRE = 5
const.RELEASING_TIME_THRE = 40
const.COUNT_GOAL_LOOP_THRE = 50
const.DISTANCE_THRE_START=400.0#以下4つは超音波センサの閾値
const.COUNT_DISTANCE_LOOP_THRE_START=40
const.DISTANCE_THRE_END=50.0
const.COUNT_DISTANCE_LOOP_THRE_END=40
const.AREA_THRE_END=20000#以下7つはカメラに関する閾値
const.COUNT_AREA_LOOP_THRE_END=30
const.AREA_THRE_LOSE=50
const.COUNT_AREA_LOOP_THRE_LOSE=70
const.AREA_THRE_START=2500
const.COUNT_AREA_LOOP_THRE_START=10
const.COG_THRE_START=15000
    
    